### ISSUE TITLE
Missing Docs

### ISSUE THREAD

**Issue by philippfrenzel** [borodulin/yii2-modal-form#1]
Hi,

can you pls. add some documentation about usage? CodeSnippets?

Great Thanks!

**Comment by borodulin** [comment]
Hi!
A just added a little usage in the readme file. If you have any questions - please ask me.

**Comment by philippfrenzel** [comment]
Hi,
thanks - give's a bit of a usage! ;) Anything special I have to care within the form view?

Thanks Philipp

**Comment by borodulin** [comment]
Hi!
https://borodulin.github.io/yii2-modal-form/
I added a few examples of the client library.
