### ISSUE TITLE
Custom options don`t work.

### ISSUE THREAD

**Issue by peterkocian** [borodulin/yii2-modal-form#10]
There is no possibility to add custom options to modal window eg. class, id, tabindex,.... I`ve tryied to add them as options array, but nothing happend. 

```
\conquer\modal\ModalForm::widget([
    'selector' => '.modal-form',
    'size' => 'modal-lg',
    'options' => [
        'class' => 'test-class',
        'tabindex' => false
        ]
]);
```

**Comment by borodulin** [comment]
List of supported options is here:
https://github.com/borodulin/yii2-modal-form/blob/master/assets/modal-form.js#L15-L27
Feel free to make pull request to add the required functionality.
