### ISSUE TITLE
onclick event repeat 

### ISSUE THREAD

**Issue by dingmuqi** [borodulin/yii2-modal-form#18]
1.
`\conquer\modal\ModalForm::widget([
    'selector' => '.modal-form',
    'clientOptions' => [
        'tabindex' => 'false',
    ]
]);`
2.
> echo Html::a('<span class="btn btn-sm ml-px btn-success" >button</span>', false, [
            'title' => 'button',
            'aria-label' => 'button',
            'class' => 'accountability_unit_view modal-form',
        ]);
3.

> $('.accountability_unit_view').on('click', function (e) {
           
            var keys = $('#grid-pjax').yiiGridView('getSelectedRows');
            if (keys.length == 0) {
                return false;
            }
            var params_id = [];
          
            for (var i = 0; i < keys.length; i++) {
                var obj = keys[i];
                params_id.push(obj);
            }

            params_id = params_id.join(',');
            var url = '/a-b/c-d-e-f?CU_Id=' + <?=$this->params['CU_Id'];?> + '&PP_Id=' + <?=  $PP>PP_Id?> + '&params_id=' + params_id;

            $(this).attr('href', url);

        });
when i click accountability_unit_view button one time is ok,after i close the modal,click again the ‘accountability_unit_view ’ button，ajax send 2 times.
Repeat like this
is send *2 http request
![image](https://user-images.githubusercontent.com/2850652/106561947-8ce6c100-6564-11eb-9f8c-ca1e4254f64b.png)

**Comment by borodulin** [comment]
You should put JS code that handles click event and sends data outside of xhr content. Render it once in view, and use "live" event handlers.
for example:
```
$('body').on('click', 'a.myclass', function() {
    // do something
});
```
Read more about live event handlers:
https://stackoverflow.com/questions/1359018/how-do-i-attach-events-to-dynamic-html-elements-with-jquery

**Comment by dingmuqi** [comment]
Yes, I also tried to do this, but to no avail, I will still submit http requests repeatedly. If I modify this file, some pages can be resolved, but some pages still cannot pop up the modal box.
`$('body').on('click', '{$this->selector}', function() {`  
change
`$('body').off('click').on('click', '{$this->selector}', function() {
    var options = $.extend($options, $(this).data());`

**Comment by dingmuqi** [comment]
sorry，After testing, I found that the problem is my code $(this).attr('href', url); . If I remove this code, the http request will only be sent once. but how i use dynamic url . thank you very much。

**Comment by dingmuqi** [comment]
I am very sorry to disturb you. I have found the cause of the bug. RenderAjax is used in the newly opened yii2 action and is called repeatedly on the new modal page use `\conquer\modal\ModalForm::widget([ 'selector' => '.modal-form', 'clientOptions' => [ 'tabindex' => 'false', ] ]);
is ok now. thanks very much
