### ISSUE TITLE
jquery is required for the widget

### ISSUE THREAD

**Issue by earx** [borodulin/yii2-modal-form#2]
1. If I place '<?php \conquer\modal\ModalForm::widget(['selector' => '.modal-form']); ?>' on top of page - I've got error

modal-form.js:8 Uncaught TypeError: Cannot read property 'ajaxPrefilter' of undefined

2. if I've put widget call at the page end, it works fine.

I think dependency of Yii\web\Jquery should be added to ModalFormAsset.php

**Comment by borodulin** [comment]
Fixed. Here is a slightly different solution: actually this extension is depended of BootstrapPluginAsset, that contains JQueryAsset.
