### ISSUE TITLE
options.async = true for ajax request break initializations for loaded js files

### ISSUE THREAD

**Issue by earx** [borodulin/yii2-modal-form#3]
suppose loaded form used activefom.js
if options.async = true, loaded js file is not initialised before form is displayed
 (in
  $.ajaxPrefilter(function(options, originalOptions, jqXHR) {
      options.async = true;
  });

**Comment by borodulin** [comment]
This plugin is designed to be used without activeform.js. There is now support for client validation, only server validation is used. I recommend to switch off client validation. If you have any idea how to fix it - feel free to make pull request.
