### ISSUE TITLE
Force global configuration in asynchronous mode affects other libraries

### ISSUE THREAD

**Issue by MarcoPro** [borodulin/yii2-modal-form#4]
Forcing the configuration of .Ajax to asynchronous mode causes that the rest of the libraries that use of .ajax have that configuration by defect. In the case of libraries that load JS files in lazyload mode, it can be a problem.

I have found that problem with some libraries like typeahead.

`$.ajaxPrefilter(function(options, originalOptions, jqXHR) {
        options.async = true;
});`

**Comment by borodulin** [comment]
removed. https://github.com/borodulin/yii2-modal-form/commit/548c0a678fd392c7797c75f294c8cf6c58b83e69
