### ISSUE TITLE
renderPartial or renderAjax ?

### ISSUE THREAD

**Issue by paskuale75** [borodulin/yii2-modal-form#7]
What best render option for load js+css of widgets in a form view ? [Here](https://www.yiiframework.com/doc/api/2.0/yii-web-controller#renderAjax()-detail) seem to be best solution 'renderAjax', what is the difference ?

thanks

**Comment by borodulin** [comment]
Try it in practice how it works.
I recommend making a separate layout for AJAX requests and switch to it.
```
public function render()
{
    if (Yii::$app->request->isAjax()) {
      $this->layout = 'myAjaxLayout';
    }
   return parent::render();
}

**Comment by paskuale75** [comment]
In my cases with 'renderAjax' and form with option _'enableClientValidation => false'_  works very well, I wonder if I can encounter problems this way or I can feel comfortable, why do you recommend a different layout ?

thanks

**Comment by borodulin** [comment]
Problems start when you connect third-party controls and page-level javascripts. Custom layout can help you to handle vendors js library loading.

**Comment by borodulin** [comment]
if everything is working now, you do not need to do this layout.

**Comment by paskuale75** [comment]
I've a complex form with  @kartik widgets, and it work very fine ! Thanks for this extension ;)
