### ISSUE TITLE
Conflict with bootstrap dropdown menu

### ISSUE THREAD

**Issue by Artkoha** [borodulin/yii2-modal-form#9]
Hi! Nice extension! I have a problem width your modal form and accordeon menu. The menu not open dropdown item on the same page where your modal form use.. But i haven't amy js error in my console..

**Comment by borodulin** [comment]
This is an initialization problem. You should initialize all the elements after they have been uploaded through AJAX.

**Comment by paskuale75** [comment]
conflict with bs4, If I remove asset depend on yii\bootstrap\BootstrapPluginAsset it works for me. Can be a solution ?

**Comment by borodulin** [comment]
I don't know how to help you. If you solve the problem, make a pull request.

**Comment by paskuale75** [comment]
there should be a choice between bs3 and bs4, in your code depends from bootstrap3.

**Comment by paskuale75** [comment]
PR
